Repository jahnvisahni31/DesignDeck, pull requests merged in 2024-11, with the labels that each got.

#240 Review Section Addition
  app/App.tsx
  components/ui/review.tsx
  package-lock.json
  package.json
  public/Liam.jpg
  public/ava.jpg
  public/james.jpg
  public/sophia.jpg
  public/zara.jpg
Labels: good first issue, gssoc-ext, hacktoberfest-accepted, level2, hacktoberfest

#247 fix/sign-up button ui
  app/front-navbar.tsx
Labels: good first issue, gssoc-ext, hacktoberfest-accepted, level1, hacktoberfest

#248 [Feat] / Custom scrollbar
  app/globals.css
Labels: good first issue, gssoc-ext, hacktoberfest-accepted, level1, hacktoberfest

#254 Added Project Structure.md
  Project Structure.md
Labels: good first issue, gssoc-ext, hacktoberfest-accepted, level1, hacktoberfest

#253 Add navbar in sign in and sign up page
  app/login/page.tsx
  app/signup/page.tsx
Labels: good first issue, gssoc-ext, hacktoberfest-accepted, level2, hacktoberfest

#261 Enhance the Bug Template
  .github/ISSUE_TEMPLATE/bug.yml
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: gssoc-ext, hacktoberfest-accepted, level1, hacktoberfest

#266 Added nameing input to all placeholder of login and signup page
  app/login/page.tsx
  app/signup/page.tsx
Labels: good first issue, gssoc-ext, hacktoberfest-accepted, level1, hacktoberfest

#262 Enhance the Custom Issue Template
  .github/ISSUE_TEMPLATE/custom.md
  .github/ISSUE_TEMPLATE/custom.yml
Labels: good first issue, gssoc-ext, hacktoberfest-accepted, level1, hacktoberfest

#265 Implemented navbar and footer on different pages
  app/blogs/page.tsx
  app/contact/page.tsx
  app/faq/page.tsx
  app/pricing/page.tsx
  app/privacy_policy/page.tsx
  app/support/page.tsx
  app/terms_of_use/page.tsx
Labels: good first issue, gssoc-ext, hacktoberfest-accepted, level2, hacktoberfest

#270 Add GitHub Workflow for Auto-Closing Similar Issue Requests
  .github/workflows/detect-duplicate.yml
Labels: good first issue, gssoc-ext, hacktoberfest-accepted, level2, hacktoberfest

#272 Enhance the Feature Template
  .github/ISSUE_TEMPLATE/feature.yml
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: good first issue, gssoc-ext, hacktoberfest-accepted, level1, hacktoberfest

#273 ADD Q&A Suggestion Template
  .github/ISSUE_TEMPLATE/config.yml
Labels: good first issue, gssoc-ext, hacktoberfest-accepted, level1, hacktoberfest

#274 Fix: Testimonial section dark theme
  components/ui/review.tsx
Labels: good first issue, gssoc-ext, hacktoberfest-accepted, level1, hacktoberfest
