Repository jahnvisahni31/DesignDeck, pull requests merged in 2024-10, with the labels that each got.

#81 Fixed the text and Shapes canvas
  app/workspace/page.tsx
Labels: good first issue, gssoc-ext, hacktoberfest-accepted, level1, hacktoberfest

#166 fixed the light mode bug
  app/front-navbar.tsx
Labels: bug, gssoc-ext, hacktoberfest-accepted, level1, hacktoberfest

#165 Newlogo for the website
  .eslintrc.json
  app/blogs/page.tsx
  app/front-navbar.tsx
  app/support/page.tsx
  app/workspace/page.tsx
  components/Loader.tsx
  components/comments/PinnedThread.tsx
  docker-compose.yml
  liveblocks.config.ts
  package-lock.json
  package.json
  public/assets/design-deck-logo.png
Labels: good first issue, gssoc-ext, hacktoberfest-accepted, level1, hacktoberfest

#199 Update README.md
  README.md
Labels: documentation, good first issue, gssoc-ext, hacktoberfest-accepted, level1, hacktoberfest

#200 Added Table to Display Repository Statistics in README.md
  README.md
Labels: good first issue, gssoc-ext, hacktoberfest-accepted, level1, hacktoberfest

#201 [UI Update] Changed the UI of Terms of Service page to match the UI of the site ✨
  app/front-navbar.tsx
  app/layout.tsx
  app/terms_of_use/page.tsx
Labels: good first issue, gssoc-ext, hacktoberfest-accepted, level2, hacktoberfest

#205 Done enhancements and also added some new sections
  CONTRIBUTING.md
Labels: good first issue, gssoc-ext, hacktoberfest-accepted, level1, hacktoberfest

#186 Notification is working
  app/App.tsx
  app/front-navbar.tsx
  package-lock.json
  package.json
  tsconfig.json
Labels: good first issue, gssoc-ext, hacktoberfest-accepted, level1, hacktoberfest
